#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#if IS_HNS
#define LAND_WILD_COUNT     4
#define WATER_WILD_COUNT    4
#define ROCK_WILD_COUNT     4
#define FISH_WILD_COUNT     4
#else
#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     10
#endif
#define HIDDEN_WILD_COUNT   3

#define NUM_ALTERING_CAVE_TABLES 9

#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
