gText_Oak_Welcome::
	.string "Bienvenue dans le monde de\n"
	.string "POKéMON TACTICA !\p"
	.string "Je suis le Professeur Chen.\p"
	.string "Depuis toujours, humains et POKéMON\n"
	.string "vivent, voyagent et combattent\l"
	.string "côte à côte.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Mais devenir un grand Dresseur\n"
	.string "demande bien plus que de posséder\l"
	.string "des POKéMON puissants.\p"
	.string "$"

gText_Oak_MainSpeech::
	.string "Il faut apprendre à connaître son\n"
	.string "équipe, anticiper son adversaire\l"
	.string "et savoir s'adapter à chaque combat.\p"
	.string "À Johto, les Dresseurs que tu\n"
	.string "rencontreras sont prêts à mettre\l"
	.string "tes choix à l'épreuve.\p"
	.string "Chaque Champion possède sa propre\n"
	.string "stratégie, et chaque victoire te\l"
	.string "demandera de progresser.\p"
	.string "Ton aventure te mènera à travers\n"
	.string "Johto… puis bien au-delà,\l"
	.string "jusqu'à Kanto.\p"
	.string "$"

gText_Oak_AndYouAre::
	.string "Mais avant tout… qui es-tu ?$"

gText_Oak_BoyOrGirl::
	.string "Es-tu un garçon ?\n"
	.string "Ou une fille ?$"

gText_Oak_WhatChallenge::
	.string "Quel défi recherches-tu ?$"

gText_Oak_ChallengeSelected::
	.string "Parfait. Ce défi te correspond !$"

gText_Oak_WhatsYourName::
	.string "Et quel est ton nom ?$"

gText_Oak_SoItsPlayer::
	.string "Très bien… tu t'appelles {PLAYER} ?$"

gText_Oak_YourePlayer::
	.string "{PLAYER}, construis ton équipe.\p"
	.string "Découvre de nouvelles possibilités.\p"
	.string "Et surtout… trouve ta propre façon\n"
	.string "de combattre.\p"
	.string "$"

gText_Oak_AreYouReady::
	.string "Car ici, une bonne stratégie peut\n"
	.string "faire toute la différence.\p"
	.string "Ton aventure dans POKéMON TACTICA\n"
	.string "est sur le point de commencer !\p"
	.string "$"
