#!/usr/bin/env python3
"""Generate the runtime rival roster table from data/spec/rival.json."""

from __future__ import annotations

import argparse
import json
import re
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "data/spec/rival.json"
OUTPUT = ROOT / "src/data/tactica_rival.h"


def normalize(value: str) -> str:
    ascii_value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode()
    return re.sub(r"[^A-Z0-9]", "", ascii_value.upper())


def constants(path: Path, prefix: str) -> dict[str, str]:
    result: dict[str, str] = {}
    pattern = re.compile(rf"(?:#define\s+|\s*)({prefix}[A-Z0-9_]+)\s*(?:=\s*|\s+)")
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        match = pattern.match(line)
        if match:
            name = match.group(1)
            result[normalize(name[len(prefix):])] = name
    return result


def parse_evs(value: str) -> list[int]:
    indices = {"HP": 0, "ATK": 1, "DEF": 2, "SPA": 3, "SPD": 4, "SPE": 5}
    evs = [0] * 6
    for amount, stat in re.findall(r"(\d+)\s+(HP|Atk|Def|SpA|SpD|Spe)", value):
        evs[indices[stat.upper()]] = int(amount)
    return evs


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated table is stale")
    args = parser.parse_args()
    data = json.loads(SPEC.read_text(encoding="utf-8"))
    species = constants(ROOT / "include/constants/species.h", "SPECIES_")
    moves = constants(ROOT / "include/constants/moves.h", "MOVE_")
    items = constants(ROOT / "include/constants/items.h", "ITEM_")
    phases = ("early", "mid", "final")
    lines = [
        "// Generated by tools/generate_tactica_rival.py from data/spec/rival.json.",
        "// Do not edit this file directly.",
        "static const u16 sTacticaRivalStarterItems[FAMILY_EEVEE] =",
        "{",
    ]
    for category_index, (category, mons) in enumerate(data["fight_rosters"]["categories"].items()):
        starter = next(mon for mon in mons if mon["family"] == "saved starter")
        lines.append(f"    [{category_index}] = {items[normalize(starter['final_item'])]}, // {category}")
    lines += [
        "};",
        "",
        "static const u8 sTacticaRivalHardEvs[][NUM_STATS] =",
        "{",
    ]
    for category, mons in data["fight_rosters"]["categories"].items():
        for mon in mons:
            if mon["family"] == "saved starter":
                continue
            evs = parse_evs(mon["hard_evs"])
            lines.append("    {%s}," % ", ".join(map(str, evs)))
    lines += ["};", "", "static const struct TacticaRivalMon sTacticaRivalMons[FAMILY_EEVEE][PARTY_SIZE] =", "{"]
    ev_index = 0
    for category_index, (category, mons) in enumerate(data["fight_rosters"]["categories"].items()):
        lines.append(f"    [{category_index}] = // {category}")
        lines.append("    {")
        for mon in mons:
            if mon["family"] == "saved starter":
                lines.append("        {.isSavedStarter = TRUE},")
                continue
            base = species[normalize(mon["family"])]
            target = species[normalize(mon["target_final_species"])]
            item = items[normalize(mon["final_item"])]
            nature = "NATURE_" + normalize(mon["nature"])
            phase_moves = mon["phase_moves"]
            rendered_moves = []
            for phase in phases:
                rendered_moves.append("{%s}" % ", ".join(moves[normalize(move)] for move in phase_moves[phase]))
            lines.append(
                "        {.baseSpecies = %s, .finalSpecies = %s, .moves = {%s}, "
                ".finalItem = %s, .nature = %s, .hardEvs = sTacticaRivalHardEvs[%d]},"
                % (base, target, ", ".join(rendered_moves), item, nature, ev_index)
            )
            ev_index += 1
        lines.append("    },")
    lines += ["};", ""]
    rendered = "\n".join(lines)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("generated rival table is stale; run tools/generate_tactica_rival.py")
        print("Generated rival table is current")
    else:
        OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
