#!/usr/bin/env python3
"""Generate the compact Tactica move-shop compatibility table."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LEARNABLES = ROOT / "src/data/pokemon/all_learnables.json"
MOVES = ROOT / "include/constants/moves.h"
SPECIES = ROOT / "include/constants/species.h"
OUTPUT = ROOT / "src/data/pokemon/tactica_move_shop_learnsets.h"
MAX_COMPATIBLE_MOVES = 400


def parse_enum_values() -> dict[str, int]:
    text = MOVES.read_text(encoding="utf-8")
    body = text.split("enum __attribute__((packed)) Move", 1)[1].split("};", 1)[0]
    values: dict[str, int] = {}
    current = -1
    for raw_line in body.splitlines():
        line = raw_line.split("//", 1)[0].strip().rstrip(",")
        if not line or not re.match(r"^[A-Z][A-Z0-9_]*(?:\s*=|$)", line):
            continue
        if "=" in line:
            name, expression = (part.strip() for part in line.split("=", 1))
            if expression.isdigit():
                current = int(expression)
            elif expression in values:
                current = values[expression]
            else:
                raise ValueError(f"unsupported move enum expression: {line}")
        else:
            name = line
            current += 1
        values[name] = current
    return values


def build_output() -> str:
    move_values = parse_enum_values()
    move_count = move_values["MOVES_COUNT"]
    bitset_size = (move_count + 7) // 8
    species_definitions = dict(re.findall(
        r"^#define SPECIES_([A-Z0-9_]+)\s+(?:SPECIES_)?([A-Z0-9_]+)",
        SPECIES.read_text(encoding="utf-8"),
        re.M,
    ))
    species_values: dict[str, int] = {}
    unresolved = dict(species_definitions)
    while unresolved:
        progress = False
        for name, value in list(unresolved.items()):
            if value.isdigit():
                species_values[name] = int(value)
            elif value in species_values:
                species_values[name] = species_values[value]
            else:
                continue
            del unresolved[name]
            progress = True
        if not progress:
            break
    canonical_species = {
        value: name
        for name, value in species_values.items()
        if species_definitions[name].isdigit()
    }
    raw_learnables = json.loads(LEARNABLES.read_text(encoding="utf-8"))
    learnables: dict[int, set[str]] = {}

    for raw_species, moves in raw_learnables.items():
        species = "FLABEBE" if raw_species.startswith("FLAB") and raw_species not in species_values else raw_species
        if species not in species_values:
            raise ValueError(f"unknown species in all_learnables.json: {raw_species}")
        learnables.setdefault(species_values[species], set()).update(moves)

    active_moves = {
        move
        for moves in learnables.values()
        for move in moves
        if move in move_values and 0 < move_values[move] < move_count and move != "MOVE_STRUGGLE"
    }
    largest_movepool = max(
        sum(
            1
            for move in moves
            if move in move_values and 0 < move_values[move] < move_count and move != "MOVE_STRUGGLE"
        )
        for moves in learnables.values()
    )
    if largest_movepool >= MAX_COMPATIBLE_MOVES:
        raise ValueError(
            f"largest move-shop list has {largest_movepool} moves; "
            f"MAX_RELEARNER_MOVES must exceed it"
        )

    lines = [
        "// Generated by tools/sync_tactica_move_shop.py. Do not edit by hand.",
        f"// {len(active_moves)} active moves across {len(learnables)} species/form entries; largest list: {largest_movepool}.",
        "#define TACTICA_MOVE_SHOP_BITSET_SIZE ((MOVES_COUNT + 7) / 8)",
        "",
        "static const u8 sTacticaMoveShopLearnsets[NUM_SPECIES][TACTICA_MOVE_SHOP_BITSET_SIZE] =",
        "{",
    ]
    for species_id in sorted(learnables):
        bits = [0] * bitset_size
        species = canonical_species[species_id]
        for move in learnables[species_id]:
            if move not in move_values:
                raise ValueError(f"unknown move for {species}: {move}")
            move_id = move_values[move]
            if 0 < move_id < move_count and move != "MOVE_STRUGGLE":
                bits[move_id // 8] |= 1 << (move_id % 8)
        byte_text = ", ".join(f"0x{value:02X}" for value in bits)
        lines.append(f"    [SPECIES_{species}] = {{{byte_text}}},")
    lines.extend(("};", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = build_output()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"out of date: {OUTPUT.relative_to(ROOT)}")
            return 1
        print("Tactica move-shop compatibility data is up to date")
        return 0
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
