#!/usr/bin/env python3
"""Generate Headbutt/Safari data from the same canonical tables as the wiki."""

from __future__ import annotations
import argparse
from collections import OrderedDict
import json
from functools import lru_cache
from pathlib import Path
import re
from generate_tactica_rival import constants, normalize

ROOT = Path(__file__).resolve().parents[1]
FORM_ALIASES = {
    "Deerling (Spring Form)": "Deerling-Spring",
    "Burmy (Plant Cloak)": "Burmy-Plant",
    "Furfrou (Natural Form)": "Furfrou",
}


@lru_cache(maxsize=None)
def species_constant(name):
    if name.startswith("SPECIES_"):
        return name
    ids = constants(ROOT / "include/constants/species.h", "SPECIES_")
    return ids[normalize(FORM_ALIASES.get(name, name))]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    tables = json.loads((ROOT / "data/spec/encounters_special.json").read_text())[
        "tables"
    ]
    legacy_path = ROOT / "data/family_remix/special_encounter_pools.json"
    legacy = json.loads(legacy_path.read_text())
    by_key = {(t["map"], t["method"]): t for t in tables}
    for t in legacy["tables"]:
        canonical = by_key[(t["map"], t["method"])]
        for key in ("species", "min_level", "max_level", "rates"):
            t[key] = canonical[key]
    outputs = {legacy_path: json.dumps(legacy, ensure_ascii=False, indent=2) + "\n"}
    path = ROOT / "src/data/family_remix_headbutt.h"
    source = path.read_text()
    arrays = re.findall(
        r"static const struct WildPokemon (\w+)\[\]\s*=\s*\{.*?\};", source, re.S
    )
    headbutt = [t for t in tables if t["method"] == "headbutt_mons"]
    if len(arrays) != len(headbutt):
        raise ValueError("Headbutt table count mismatch")
    for name, t in zip(arrays, headbutt):
        body = "static const struct WildPokemon " + name + "[] =\n{\n"
        for mon in t["species"]:
            body += f"    {{{t['min_level']}, {t['max_level']}, {species_constant(mon)}}},\n"
        body += "};"
        source = re.sub(
            r"static const struct WildPokemon " + name + r"\[\]\s*=\s*\{.*?\};",
            lambda _: body,
            source,
            flags=re.S,
        )
    outputs[path] = source
    sectors = OrderedDict()
    for t in tables:
        if t["method"] != "headbutt_mons":
            sectors.setdefault(t["map"], []).append(t)
    source = "// Generated by tools/sync_tactica_special_encounters.py from data/spec/encounters_special.json.\n\n"
    for map_id, pools in sectors.items():
        name = "sFamilySafari" + "".join(
            p.title() for p in map_id.removeprefix("MAP_").split("_")
        )
        source += f"static const struct FamilySafariPool {name}[] =\n{{\n"
        for t in pools:
            mons = ", ".join(map(species_constant, t["species"]))
            source += f"    {{\n        .minLevel = {t['min_level']},\n        .maxLevel = {t['max_level']},\n        .species = {{{mons}}},\n    }},\n"
        source += "};\n\n"
    source += "static const struct FamilySafariSector sFamilySafariSectors[] =\n{\n"
    for map_id, pools in sectors.items():
        name = "sFamilySafari" + "".join(
            p.title() for p in map_id.removeprefix("MAP_").split("_")
        )
        source += (
            f"    {{MAP_GROUP({map_id}), MAP_NUM({map_id}), {len(pools)}, {name}}},\n"
        )
    source += "};\n"
    outputs[ROOT / "src/data/family_remix_safari.h"] = source
    stale = []
    for path, expected in outputs.items():
        if path.read_text() != expected:
            stale.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.write_text(expected)
    if stale and args.check:
        raise SystemExit("Stale special encounters: " + ", ".join(stale))
    print(
        "Tactica special encounters: "
        + ("checked" if args.check else "synchronized")
        + " 4 Headbutt tables and 53 Safari pools"
    )


if __name__ == "__main__":
    main()
