#!/usr/bin/env python3
"""Generate the Tactica Mega Stone vendor from playable item form changes."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FORM_CHANGES_PATH = ROOT / "src/data/pokemon/form_change_tables.h"
ITEMS_PATH = ROOT / "src/data/items.h"
OUTPUT_PATH = ROOT / "data/scripts/mega_shop.inc"
MEGA_STONE_PRICE = 3000


def playable_mega_stones() -> list[str]:
    source = FORM_CHANGES_PATH.read_text(encoding="utf-8")
    items = sorted(set(re.findall(
        r"FORM_CHANGE_BATTLE_MEGA_EVOLUTION_ITEM,\s+SPECIES_[A-Z0-9_]+,\s+(ITEM_[A-Z0-9_]+)",
        source,
    )))
    if len(items) != 92:
        raise SystemExit(f"Expected 92 playable Mega Stones, found {len(items)}")
    return items


def render(items: list[str]) -> str:

    lines = [
        "@ Generated by tools/sync_tactica_mega_shop.py from playable form changes.",
        "MegaShop_EventScript::",
        "\tlock",
        "\tfaceplayer",
        "\tmsgbox MegaShop_Text_Welcome, MSGBOX_DEFAULT",
        "\tpokemart MegaShop_Items",
        "\tmsgbox gText_PleaseComeAgain, MSGBOX_DEFAULT",
        "\trelease",
        "\tend",
        "",
        "MegaShop_Text_Welcome:",
        "\t.string \"Every Mega Stone supported by our\\n\"",
        "\t.string \"battle system is available here.$\"",
        "",
        "\t.align 2",
        "MegaShop_Items::",
    ]
    lines.extend(f"\t.2byte {item}" for item in items)
    lines.extend(["\tpokemartlistend", ""])
    return "\n".join(lines)


def render_items_with_prices(items: list[str]) -> str:
    source = ITEMS_PATH.read_text(encoding="utf-8")
    for item in items:
        pattern = re.compile(
            rf"(\[{item}\]\s*=\s*\{{(?:(?!\n\s*\[ITEM_).)*?\.price\s*=\s*)\d+(,)",
            re.DOTALL,
        )
        source, count = pattern.subn(rf"\g<1>{MEGA_STONE_PRICE}\2", source, count=1)
        if count != 1:
            raise SystemExit(f"Could not set a unique price for {item}")
    return source


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    check = parser.parse_args().check
    items = playable_mega_stones()
    generated = render(items)
    priced_items = render_items_with_prices(items)
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    current_items = ITEMS_PATH.read_text(encoding="utf-8")
    if check:
        if current != generated:
            raise SystemExit("Mega Stone shop is not synchronized; run tools/sync_tactica_mega_shop.py")
        if current_items != priced_items:
            raise SystemExit(
                f"Playable Mega Stones must all cost {MEGA_STONE_PRICE}; "
                "run tools/sync_tactica_mega_shop.py"
            )
        return
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    ITEMS_PATH.write_text(priced_items, encoding="utf-8")


if __name__ == "__main__":
    main()
