#!/usr/bin/env python3
"""Generate the Tactica Mega Stone vendor from playable item form changes."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FORM_CHANGES_PATH = ROOT / "src/data/pokemon/form_change_tables.h"
OUTPUT_PATH = ROOT / "data/scripts/mega_shop.inc"


def render() -> str:
    source = FORM_CHANGES_PATH.read_text(encoding="utf-8")
    items = sorted(set(re.findall(
        r"FORM_CHANGE_BATTLE_MEGA_EVOLUTION_ITEM,\s+SPECIES_[A-Z0-9_]+,\s+(ITEM_[A-Z0-9_]+)",
        source,
    )))
    if len(items) != 92:
        raise SystemExit(f"Expected 92 playable Mega Stones, found {len(items)}")

    lines = [
        "@ Generated by tools/sync_tactica_mega_shop.py from playable form changes.",
        "MegaShop_EventScript::",
        "\tlock",
        "\tfaceplayer",
        "\tmsgbox MegaShop_Text_Welcome, MSGBOX_DEFAULT",
        "\tpokemart MegaShop_Items",
        "\tmsgbox gText_PleaseComeAgain, MSGBOX_DEFAULT",
        "\trelease",
        "\tend",
        "",
        "MegaShop_Text_Welcome:",
        "\t.string \"Every Mega Stone supported by our\\n\"",
        "\t.string \"battle system is available here.$\"",
        "",
        "\t.align 2",
        "MegaShop_Items:",
    ]
    lines.extend(f"\t.2byte {item}" for item in items)
    lines.extend(["\tpokemartlistend", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    check = parser.parse_args().check
    generated = render()
    current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if check:
        if current != generated:
            raise SystemExit("Mega Stone shop is not synchronized; run tools/sync_tactica_mega_shop.py")
        return
    OUTPUT_PATH.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
