// Generated by tools/sync_tactica_special_encounters.py from data/spec/encounters_special.json.

static const struct FamilySafariPool sFamilySafariSafariZoneTopLeftHns[] =
{
    {
        .minLevel = 37,
        .maxLevel = 40,
        .species = {SPECIES_BEEDRILL, SPECIES_SAWSBUCK_SPRING, SPECIES_DUSTOX, SPECIES_WIGGLYTUFF},
    },
    {
        .minLevel = 37,
        .maxLevel = 40,
        .species = {SPECIES_BEAUTIFLY, SPECIES_BUTTERFREE, SPECIES_LEDIAN, SPECIES_YANMA},
    },
    {
        .minLevel = 37,
        .maxLevel = 40,
        .species = {SPECIES_COMBEE, SPECIES_JUMPLUFF, SPECIES_IGGLYBUFF, SPECIES_TROPIUS},
    },
    {
        .minLevel = 37,
        .maxLevel = 40,
        .species = {SPECIES_ILLUMISE, SPECIES_KARRABLAST, SPECIES_MIME_JR, SPECIES_VOLBEAT},
    },
    {
        .minLevel = 37,
        .maxLevel = 40,
        .species = {SPECIES_BURMY_PLANT, SPECIES_KRICKETUNE, SPECIES_SHELMET, SPECIES_MARACTUS},
    },
};

static const struct FamilySafariPool sFamilySafariSafariZoneTopMidHns[] =
{
    {
        .minLevel = 38,
        .maxLevel = 41,
        .species = {SPECIES_DEDENNE, SPECIES_XATU, SPECIES_WOOBAT, SPECIES_GIRAFARIG},
    },
    {
        .minLevel = 38,
        .maxLevel = 41,
        .species = {SPECIES_DACHSBUN, SPECIES_GRANBULL, SPECIES_SPRITZEE, SPECIES_SWIRLIX},
    },
    {
        .minLevel = 38,
        .maxLevel = 41,
        .species = {SPECIES_CLEFFA, SPECIES_MILCERY, SPECIES_TOGEPI, SPECIES_ESPURR},
    },
    {
        .minLevel = 38,
        .maxLevel = 41,
        .species = {SPECIES_HYPNO, SPECIES_MUNNA, SPECIES_GRUMPIG, SPECIES_ELGYEM},
    },
    {
        .minLevel = 38,
        .maxLevel = 41,
        .species = {SPECIES_STOUTLAND, SPECIES_DUBWOOL, SPECIES_WOBBUFFET, SPECIES_CHINGLING},
    },
};

static const struct FamilySafariPool sFamilySafariSafariZoneLowMidHns[] =
{
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_CHATOT, SPECIES_DODRIO, SPECIES_FARFETCHD, SPECIES_STUNFISK},
    },
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_EMOLGA, SPECIES_FURFROU, SPECIES_NOCTOWL, SPECIES_KOMALA},
    },
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_CASTFORM, SPECIES_KECLEON, SPECIES_ZANGOOSE, SPECIES_STANTLER},
    },
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_AIPOM, SPECIES_LICKITUNG, SPECIES_SPINDA, SPECIES_DUNSPARCE},
    },
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_PURUGLY, SPECIES_MINCCINO, SPECIES_GREEDENT, SPECIES_BUNEARY},
    },
};

static const struct FamilySafariPool sFamilySafariSafariZoneTopRightHns[] =
{
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_CLAMPERL, SPECIES_PYUKUMUKU, SPECIES_QWILFISH, SPECIES_ALOMOMOLA},
    },
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_SWANNA, SPECIES_PANPOUR, SPECIES_GOGOAT, SPECIES_CARNIVINE},
    },
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_MEGANIUM, SPECIES_PANSAGE, SPECIES_GRAFAIAI, SPECIES_CACTURNE},
    },
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_ELDEGOSS, SPECIES_NUZLEAF, SPECIES_SUNKERN, SPECIES_CHERRIM_OVERCAST},
    },
    {
        .minLevel = 39,
        .maxLevel = 42,
        .species = {SPECIES_MINUN, SPECIES_PACHIRISU, SPECIES_PLUSLE, SPECIES_PINCURCHIN},
    },
};

static const struct FamilySafariPool sFamilySafariSafariZoneLowLeftHns[] =
{
    {
        .minLevel = 40,
        .maxLevel = 43,
        .species = {SPECIES_LUNATONE, SPECIES_NOSEPASS, SPECIES_SOLROCK, SPECIES_KLAWF},
    },
    {
        .minLevel = 40,
        .maxLevel = 43,
        .species = {SPECIES_BONSLY, SPECIES_KLEFKI, SPECIES_PANSEAR, SPECIES_ORTHWORM},
    },
    {
        .minLevel = 40,
        .maxLevel = 43,
        .species = {SPECIES_ESPATHRA, SPECIES_WATCHOG, SPECIES_SKITTY, SPECIES_BRONZONG},
    },
    {
        .minLevel = 40,
        .maxLevel = 43,
        .species = {SPECIES_BIBAREL, SPECIES_SMEARGLE, SPECIES_YUNGOOS, SPECIES_LECHONK},
    },
    {
        .minLevel = 40,
        .maxLevel = 43,
        .species = {SPECIES_DIGGERSBY, SPECIES_HAPPINY, SPECIES_EXPLOUD, SPECIES_LINOONE},
    },
};

static const struct FamilySafariPool sFamilySafariSafariZoneLowRightHns[] =
{
    {
        .minLevel = 41,
        .maxLevel = 44,
        .species = {SPECIES_DELIBIRD, SPECIES_JELLICENT, SPECIES_JYNX, SPECIES_MABOSSTIFF},
    },
    {
        .minLevel = 41,
        .maxLevel = 44,
        .species = {SPECIES_BRAMBLIN, SPECIES_THIEVUL, SPECIES_LIEPARD, SPECIES_INKAY},
    },
    {
        .minLevel = 41,
        .maxLevel = 44,
        .species = {SPECIES_GREAVARD, SPECIES_MIGHTYENA, SPECIES_COFAGRIGUS, SPECIES_DRIFBLIM},
    },
    {
        .minLevel = 41,
        .maxLevel = 44,
        .species = {SPECIES_PICHU, SPECIES_POIPOLE, SPECIES_SKUNTANK, SPECIES_SEVIPER},
    },
    {
        .minLevel = 41,
        .maxLevel = 44,
        .species = {SPECIES_SWALOT, SPECIES_HARIYAMA, SPECIES_GARBODOR, SPECIES_FALINKS},
    },
};

static const struct FamilySafariPool sFamilySafariFuchsiaCitySafariZoneBeachHns[] =
{
    {
        .minLevel = 68,
        .maxLevel = 72,
        .species = {SPECIES_POLIWRATH, SPECIES_PRIMARINA, SPECIES_QUAQUAVAL, SPECIES_SWAMPERT},
    },
    {
        .minLevel = 68,
        .maxLevel = 72,
        .species = {SPECIES_GRENINJA, SPECIES_INTELEON, SPECIES_KINGDRA, SPECIES_WALKING_WAKE},
    },
    {
        .minLevel = 68,
        .maxLevel = 72,
        .species = {SPECIES_BLASTOISE, SPECIES_EMPOLEON, SPECIES_SAMUROTT, SPECIES_FERALIGATR},
    },
    {
        .minLevel = 68,
        .maxLevel = 72,
        .species = {SPECIES_CHARIZARD, SPECIES_LUDICOLO, SPECIES_POLITOED, SPECIES_SLITHER_WING},
    },
    {
        .minLevel = 68,
        .maxLevel = 72,
        .species = {SPECIES_BUZZWOLE, SPECIES_IRON_BUNDLE, SPECIES_PHEROMOSA, SPECIES_IRON_VALIANT},
    },
    {
        .minLevel = 68,
        .maxLevel = 72,
        .species = {SPECIES_CLEFABLE, SPECIES_MILTANK, SPECIES_STOUTLAND, SPECIES_SLAKING},
    },
};

static const struct FamilySafariPool sFamilySafariFuchsiaCitySafariZoneCaveHns[] =
{
    {
        .minLevel = 71,
        .maxLevel = 75,
        .species = {SPECIES_IRON_CROWN, SPECIES_ROARING_MOON, SPECIES_SPIRITOMB, SPECIES_IRON_BOULDER},
    },
    {
        .minLevel = 71,
        .maxLevel = 75,
        .species = {SPECIES_GENGAR, SPECIES_NIHILEGO, SPECIES_OBSTAGOON, SPECIES_GUZZLORD},
    },
    {
        .minLevel = 71,
        .maxLevel = 75,
        .species = {SPECIES_BELLOSSOM, SPECIES_MEGANIUM, SPECIES_SHIFTRY, SPECIES_IRON_JUGULIS},
    },
    {
        .minLevel = 71,
        .maxLevel = 75,
        .species = {SPECIES_ALAKAZAM, SPECIES_CELESTEELA, SPECIES_SIGILYPH, SPECIES_FLUTTER_MANE},
    },
    {
        .minLevel = 71,
        .maxLevel = 75,
        .species = {SPECIES_EXPLOUD, SPECIES_MACHAMP, SPECIES_MR_RIME, SPECIES_CROBAT},
    },
    {
        .minLevel = 71,
        .maxLevel = 75,
        .species = {SPECIES_AMPHAROS, SPECIES_DURANT, SPECIES_RAICHU, SPECIES_XURKITREE},
    },
};

static const struct FamilySafariPool sFamilySafariFuchsiaCitySafariZoneMountainHns[] =
{
    {
        .minLevel = 72,
        .maxLevel = 76,
        .species = {SPECIES_FLYGON, SPECIES_IRON_TREADS, SPECIES_STAKATAKA, SPECIES_GOUGING_FIRE},
    },
    {
        .minLevel = 72,
        .maxLevel = 76,
        .species = {SPECIES_GREAT_TUSK, SPECIES_INFERNAPE, SPECIES_SANDY_SHOCKS, SPECIES_IRON_THORNS},
    },
    {
        .minLevel = 72,
        .maxLevel = 76,
        .species = {SPECIES_BLAZIKEN, SPECIES_CARBINK, SPECIES_EMBOAR, SPECIES_RAGING_BOLT},
    },
    {
        .minLevel = 72,
        .maxLevel = 76,
        .species = {SPECIES_BLACEPHALON, SPECIES_DURANT, SPECIES_TYPHLOSION, SPECIES_IRON_MOTH},
    },
    {
        .minLevel = 72,
        .maxLevel = 76,
        .species = {SPECIES_CINDERACE, SPECIES_INCINEROAR, SPECIES_SKELEDIRGE, SPECIES_DELPHOX},
    },
    {
        .minLevel = 72,
        .maxLevel = 76,
        .species = {SPECIES_DRUDDIGON, SPECIES_HEATMOR, SPECIES_PAWMOT, SPECIES_IRON_HANDS},
    },
};

static const struct FamilySafariPool sFamilySafariFuchsiaCitySafariZoneBrushHns[] =
{
    {
        .minLevel = 69,
        .maxLevel = 73,
        .species = {SPECIES_ARBOLIVA, SPECIES_LEAVANNY, SPECIES_VICTREEBEL, SPECIES_VENUSAUR},
    },
    {
        .minLevel = 69,
        .maxLevel = 73,
        .species = {SPECIES_JUMPLUFF, SPECIES_ORBEETLE, SPECIES_SCOLIPEDE, SPECIES_IRON_LEAVES},
    },
    {
        .minLevel = 69,
        .maxLevel = 73,
        .species = {SPECIES_GARDEVOIR, SPECIES_KARTANA, SPECIES_TOGEKISS, SPECIES_SCREAM_TAIL},
    },
    {
        .minLevel = 69,
        .maxLevel = 73,
        .species = {SPECIES_MEOWSCARADA, SPECIES_RILLABOOM, SPECIES_SCEPTILE, SPECIES_BRUTE_BONNET},
    },
    {
        .minLevel = 69,
        .maxLevel = 73,
        .species = {SPECIES_CHESNAUGHT, SPECIES_SERPERIOR, SPECIES_TORTERRA, SPECIES_DECIDUEYE},
    },
};

static const struct FamilySafariSector sFamilySafariSectors[] =
{
    {MAP_GROUP(MAP_SAFARI_ZONE_TOP_LEFT_HNS), MAP_NUM(MAP_SAFARI_ZONE_TOP_LEFT_HNS), 5, sFamilySafariSafariZoneTopLeftHns},
    {MAP_GROUP(MAP_SAFARI_ZONE_TOP_MID_HNS), MAP_NUM(MAP_SAFARI_ZONE_TOP_MID_HNS), 5, sFamilySafariSafariZoneTopMidHns},
    {MAP_GROUP(MAP_SAFARI_ZONE_LOW_MID_HNS), MAP_NUM(MAP_SAFARI_ZONE_LOW_MID_HNS), 5, sFamilySafariSafariZoneLowMidHns},
    {MAP_GROUP(MAP_SAFARI_ZONE_TOP_RIGHT_HNS), MAP_NUM(MAP_SAFARI_ZONE_TOP_RIGHT_HNS), 5, sFamilySafariSafariZoneTopRightHns},
    {MAP_GROUP(MAP_SAFARI_ZONE_LOW_LEFT_HNS), MAP_NUM(MAP_SAFARI_ZONE_LOW_LEFT_HNS), 5, sFamilySafariSafariZoneLowLeftHns},
    {MAP_GROUP(MAP_SAFARI_ZONE_LOW_RIGHT_HNS), MAP_NUM(MAP_SAFARI_ZONE_LOW_RIGHT_HNS), 5, sFamilySafariSafariZoneLowRightHns},
    {MAP_GROUP(MAP_FUCHSIA_CITY_SAFARI_ZONE_BEACH_HNS), MAP_NUM(MAP_FUCHSIA_CITY_SAFARI_ZONE_BEACH_HNS), 6, sFamilySafariFuchsiaCitySafariZoneBeachHns},
    {MAP_GROUP(MAP_FUCHSIA_CITY_SAFARI_ZONE_CAVE_HNS), MAP_NUM(MAP_FUCHSIA_CITY_SAFARI_ZONE_CAVE_HNS), 6, sFamilySafariFuchsiaCitySafariZoneCaveHns},
    {MAP_GROUP(MAP_FUCHSIA_CITY_SAFARI_ZONE_MOUNTAIN_HNS), MAP_NUM(MAP_FUCHSIA_CITY_SAFARI_ZONE_MOUNTAIN_HNS), 6, sFamilySafariFuchsiaCitySafariZoneMountainHns},
    {MAP_GROUP(MAP_FUCHSIA_CITY_SAFARI_ZONE_BRUSH_HNS), MAP_NUM(MAP_FUCHSIA_CITY_SAFARI_ZONE_BRUSH_HNS), 5, sFamilySafariFuchsiaCitySafariZoneBrushHns},
};
